#!/bin/sh -e

# Amount to trim from the top and bottom each ordinary PDF. This is the height
# of an A4 sheet divided by four (so we trim half a sheets worth overall).
TRIM=86mm

cd $(dirname $0)

DEST=./printing

mkdir -p $DEST

for f in comp/comp-TOKEN-128.pdf \
    comp/comp-TOKEN-129.pdf \
    comp/comp-TOKEN-130.pdf \
    comp/comp-TOKEN-131.pdf
do
    dest=${DEST}/$(basename $f)
    dest=${dest%.pdf}-2x1.pdf
    pdfjam --trim "0 $TRIM 0 $TRIM" --outfile tmp.pdf --papersize '{210mm,125mm}' $f
    pdfjam --nup 1x2 --outfile $dest tmp.pdf tmp.pdf
    rm tmp.pdf
done


pdfjam --outfile ${DEST}/comp-TOKEN-all-2x1.pdf \
    ${DEST}/comp-TOKEN-128-2x1.pdf \
    ${DEST}/comp-TOKEN-129-2x1.pdf \
    ${DEST}/comp-TOKEN-130-2x1.pdf \
    ${DEST}/comp-TOKEN-131-2x1.pdf
